# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane  :distribute do
    cocoapods()
    get_certificates           # invokes cert
    get_provisioning_profile
    enable_automatic_code_signing(path: "Runner.xcodeproj")
    build_ios_app(skip_codesigning: true, skip_profile_detection: true)

    firebase_app_distribution(
        app: "1:391339950858:ios:61710596957278064a70f3",
        testers: "cgrad@thoughtworks.com",
        release_notes: "Lots of amazing new features to test out!",
    )
  end
end


